apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: wedding-ingress
  namespace: wedding-site
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  ingressClassName: traefik
  tls:
    - hosts:
        - elitewe.com.ge
        - www.elitewe.com.ge
      secretName: elitewe-tls
  rules:
    - host: elitewe.com.ge
      http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: wedding-backend
                port:
                  number: 4000
          - path: /health
            pathType: Prefix
            backend:
              service:
                name: wedding-backend
                port:
                  number: 4000
          - path: /
            pathType: Prefix
            backend:
              service:
                name: wedding-frontend
                port:
                  number: 80
    - host: www.elitewe.com.ge
      http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: wedding-backend
                port:
                  number: 4000
          - path: /health
            pathType: Prefix
            backend:
              service:
                name: wedding-backend
                port:
                  number: 4000
          - path: /
            pathType: Prefix
            backend:
              service:
                name: wedding-frontend
                port:
                  number: 80
