apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: wedding-frontend-ingress
  namespace: wedding-site
spec:
  podSelector:
    matchLabels:
      app: wedding-frontend
  policyTypes:
    - Ingress
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: kube-system
          podSelector:
            matchLabels:
              app.kubernetes.io/name: traefik
      ports:
        - protocol: TCP
          port: 80
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: wedding-backend-ingress
  namespace: wedding-site
spec:
  podSelector:
    matchLabels:
      app: wedding-backend
  policyTypes:
    - Ingress
  ingress:
    - from:
        - podSelector:
            matchLabels:
              app: wedding-frontend
      ports:
        - protocol: TCP
          port: 4000
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: kube-system
          podSelector:
            matchLabels:
              app.kubernetes.io/name: traefik
      ports:
        - protocol: TCP
          port: 4000
